version: 2.1

orbs: 
        node: circleci/node@1.1.0
jobs:
        build:
                executor:
                        name: node/default
                        tag: '10.4'

                steps:
                        - checkout
                        - run: cd TDD_Assignment
                        - run: npm install mocha
                        - run: alias mocha='./node_modules/.bin/_mocha'
                        - run: npm install
                        - run: npm start 
