version: 2.1

orbs: 
        node: circleci/node@1.1.0
jobs:
        build:
                executor:
                        name: node/default
                        tag: '10.4'

                steps:
                        - checkout
                        - run: cd nextjs-blog
                        - run: npm install mocha
                        - run: alias mocha='./node_modules/.bin/_mocha'
                        - run: npm install
                        - run:
                                command: npm run dev
                                background: true
                        - run: sleep 5
                        - run: npm run test

