version: 2.1

orbs: 
        node: circleci/node@1.1.0
jobs:
        build:
                executor:
                        name: node/default
                        tag: '10.4'

                steps:
                        - checkout
                        - run: ls ../ -alt
                        - run: ls -alt
