version: 2.1

orbs: 
        node: circleci/node@1.1.0
jobs:
        build:
                executor:
                        name: node/default
                        tag: '10.4'
                working_directory: ~/nextjs-blog
                        
                steps:
                        - checkout
                        - run: cd nextjs-blog; npm install mocha
                        - run: cd nextjs-blog; alias mocha='./node_modules/.bin/_mocha'
                        - run: cd nextjs-blog; npm install
                        - run : ls
                        - run:
                                command: cd nextjs-blog/; npm run dev
                                background: true
                        - run: sleep 100
                        - run: cd nextjs-blog; npm run test

